[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fwe-model"
version = "0.1.0"
description = "Posture-aware Food-Water-Energy model"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
